# One Dark by Giuseppe Cesarano, https://github.com/GiuseppeCesarano
# This work is licensed under the terms of the GPL-2.0 license.
# For a copy, see https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html.


foreground #a7aab0              
background #232326              
cursor #818387                  

color0  #101012                 
color1  #de5d68                 
color2  #8fb573                 
color3  #dbb671                 
color4  #57a5e5                 
color5  #bb70d2                 
color6  #51a8b3                 
color7  #a7aab0                 

color8  #5a5b5e                 
color9  #c49060                 
color10 #8fb573                 
color11 #dbb671                 
color12 #57a5e5                 
color13 #bb70d2                 
color14 #51a8b3                 
color15 #a7aab0                 

selection_foreground #232326    
selection_background #a7aab0    

