# vim:ft=kitty
## name:     OneDark-Pro-Warmer
## author:   navarasu (adapted for Kitty)
## license:  MIT
## blurb:    Kitty theme matching navarasu/onedark.nvim warmer style

foreground              #A7AAB0
background              #232326
selection_foreground    #232326
selection_background    #A7AAB0

cursor                  #A7AAB0
cursor_text_color       #232326

url_color               #51A8B3

active_tab_foreground   #232326
active_tab_background   #A7AAB0
inactive_tab_foreground #A7AAB0
inactive_tab_background #232326

# black
color0  #1B1C1E
color8  #5A5B5E

# red
color1  #DE5D68
color9  #833B3B

# green
color2  #8FB573
color10 #282B26

# yellow
color3  #C49060
color11 #DBB671

# blue
color4  #57A5E5
color12 #68AEE8

# purple
color5  #BB70D2
color13 #79428A

# cyan
color6  #51A8B3
color14 #2B5D63

# white
color7  #A7AAB0
color15 #818387
